### ISSUE TITLE
setup() function creates an iteration metric

### ISSUE THREAD

**Issue by sniku** [grafana/k6#1605]
`setup()` creates an iteration metric.

## Environment

- k6 version: 0.27.0
- OS and version: Linux / cloud execution

## Expected Behavior

I expected to see a single iteration.

## Actual Behavior
`setup()` function created a separate iteration. Interestingly the `teardown()` function doesn't create a new iteration.

## script
```javascript
import http from 'k6/http'
import { sleep } from 'k6';

export let options = {
  iterations: 1,
  vus: 1
}

export function setup() { // creates 1 iteration
  let res = http.get('http://test.k6.io?where=setup')
}
export default function () { // created 1 iteration
  sleep(10);
  let res = http.get('http://test.k6.io?where=defaultfunction')
}

export function teardown() { // created 0 iterations
  let res = http.get('http://test.k6.io?where=teardown')
}
```

Cloud link: https://app.k6.io/runs/public/7c0d02656de748608dfd68eed2f701c2

![image](https://user-images.githubusercontent.com/442646/91162420-59a62900-e6cc-11ea-8183-563cb87a8af0.png)

Unrelated side note: It's interesting that the total count of requests is 2. The request from the `teardown()` function isn't counted.

**Comment by na--** [comment]
This is the problem on the k6 side: https://github.com/loadimpact/k6/blob/c68a4eb450aa0a806b16bef3206ba2163f05e2a7/stats/cloud/collector.go#L321-L324
Though the backend also makes a similar assumption, so we'll have to fix that as well, to fully resolve this.

**Comment by mstoykov** [comment]
This was fixed in https://github.com/grafana/k6/pull/1203 

But it still emit `iteration_duration` which is a bit strange IMO :thinking: 

Do you want to close this @sniku?

**Comment by sniku** [comment]
This is still not fully fixed. 
While the `iterations` metric works as expected, we still get `iteration_duration` for both setup and teardown. 
Maybe the description of the issue should be updated.

Running the above script on the latest k6 produces these metrics.

```k6 run iteration.js -o json```

Skipped most of the output for brevity
```
{"metric":"iterations","type":"Point","data":{"time":"2023-05-26T17:38:06.398199157+02:00","value":1,"tags":{"group":"","scenario":"default"}}}
{"metric":"iteration_duration","type":"Point","data":{"time":"2023-05-26T17:37:56.397823015+02:00","value":579.611035,"tags":{"group":"::setup"}}}
{"metric":"iteration_duration","type":"Point","data":{"time":"2023-05-26T17:38:06.398199157+02:00","value":10000.315426,"tags":{"group":"","scenario":"default"}}}
{"metric":"iteration_duration","type":"Point","data":{"time":"2023-05-26T17:38:06.955321011+02:00","value":556.712433,"tags":{"group":"::teardown"}}}

```

**Comment by mstoykov** [comment]
So you want completely not emit anything from `setup` and `teardown` and their duration?

**Comment by sniku** [comment]
I think it makes sense to be consistent :-) If we don't emit iteration, we should not emit iteration_duration.
